"""Cookie import helpers for yt-dlp."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from fastapi import HTTPException, status


_HEADER = "# Netscape HTTP Cookie File\n# Generated by YTSage Server\n"
COOKIE_PROFILES = ("default", "bilibili", "youtube")


def normalize_cookie_profile(profile: str) -> str:
    normalized = profile.strip().lower()
    if normalized not in COOKIE_PROFILES:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Unsupported cookies profile.")
    return normalized


def cookie_profile_for_url(url: str) -> str:
    host = (urlparse(url).hostname or "").lower()
    if host.endswith("bilibili.com") or host.endswith("b23.tv"):
        return "bilibili"
    if host.endswith("youtube.com") or host.endswith("youtu.be") or host.endswith("googlevideo.com"):
        return "youtube"
    return "default"


def configured_cookie_profiles(config_dir: Path) -> dict[str, bool]:
    return {profile: cookie_file_path(config_dir, profile).is_file() for profile in COOKIE_PROFILES}


def cookie_file_path(config_dir: Path, profile: str) -> Path:
    profile = normalize_cookie_profile(profile)
    if profile == "default":
        return config_dir / "cookies.txt"
    return config_dir / f"cookies-{profile}.txt"


def cookie_file_for_url(config_dir: Path, url: str) -> Path | None:
    profile = cookie_profile_for_url(url)
    candidate = cookie_file_path(config_dir, profile)
    if candidate.is_file():
        return candidate
    default = cookie_file_path(config_dir, "default")
    return default if default.is_file() else None


def normalize_cookies(content: str) -> str | None:
    stripped = content.strip()
    if not stripped:
        return None
    if _looks_like_netscape(stripped):
        return stripped + "\n"
    if stripped.startswith("{") or stripped.startswith("["):
        return _json_to_netscape(stripped)
    raise HTTPException(
        status_code=status.HTTP_400_BAD_REQUEST,
        detail="Cookies must be Netscape cookies.txt format or a supported JSON cookie export.",
    )


def _looks_like_netscape(content: str) -> bool:
    lines = [line.strip() for line in content.splitlines() if line.strip() and not line.startswith("#")]
    return any(len(line.split("\t")) >= 7 for line in lines)


def _json_to_netscape(content: str) -> str:
    try:
        data = json.loads(content)
    except json.JSONDecodeError as exc:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid cookies JSON.") from exc

    cookies = _extract_cookie_list(data)
    lines = [_HEADER.rstrip()]
    for cookie in cookies:
        line = _cookie_to_netscape_line(cookie)
        if line:
            lines.append(line)
    if len(lines) == 1:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No usable cookies were found in the JSON export.",
        )
    return "\n".join(lines) + "\n"


def _extract_cookie_list(data: Any) -> list[dict[str, Any]]:
    if isinstance(data, list):
        return [item for item in data if isinstance(item, dict)]
    if isinstance(data, dict):
        for key in ("cookies", "cookie", "data"):
            value = data.get(key)
            if isinstance(value, list):
                return [item for item in value if isinstance(item, dict)]
    return []


def _cookie_to_netscape_line(cookie: dict[str, Any]) -> str | None:
    name = _string_value(cookie, "name")
    value = _string_value(cookie, "value")
    domain = _string_value(cookie, "domain") or _string_value(cookie, "host") or _string_value(cookie, "host_key")
    if not name or value is None or not domain:
        return None

    path = _string_value(cookie, "path") or "/"
    include_subdomains = "TRUE" if domain.startswith(".") or bool(cookie.get("hostOnly") is False) else "FALSE"
    secure = "TRUE" if bool(cookie.get("secure")) else "FALSE"
    expires = _expires_value(cookie)
    return "\t".join([domain, include_subdomains, path, secure, expires, name, value])


def _string_value(cookie: dict[str, Any], key: str) -> str | None:
    value = cookie.get(key)
    if value is None:
        return None
    return str(value)


def _expires_value(cookie: dict[str, Any]) -> str:
    for key in ("expirationDate", "expires", "expiry", "expiration_date"):
        value = cookie.get(key)
        if value is None:
            continue
        try:
            return str(max(0, int(float(value))))
        except (TypeError, ValueError):
            continue
    return "0"
