"""Cookie import helpers for yt-dlp."""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from fastapi import HTTPException, status


from ..models import CookieProfileStatus


_HEADER = "# Netscape HTTP Cookie File\n# Generated by YTSage Server\n"
COOKIE_PROFILES = ("default", "bilibili", "douyin", "youtube")
COOKIE_PROFILE_DOMAINS = {
    "bilibili": ".bilibili.com",
    "douyin": ".douyin.com",
    "youtube": ".youtube.com",
}
_LOGIN_STATUS_FILENAME = "cookie-login-status.json"


def normalize_cookie_profile(profile: str) -> str:
    normalized = profile.strip().lower()
    if normalized not in COOKIE_PROFILES:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Unsupported cookies profile.")
    return normalized


def _host_matches_domain(host: str, domain: str) -> bool:
    normalized = domain.lstrip(".").lower()
    return host == normalized or host.endswith(f".{normalized}")


def cookie_domain_for_profile(profile: str) -> str | None:
    return COOKIE_PROFILE_DOMAINS.get(normalize_cookie_profile(profile))


def cookie_profile_for_url(url: str) -> str:
    host = (urlparse(url).hostname or "").lower()
    if _host_matches_domain(host, "bilibili.com") or _host_matches_domain(host, "b23.tv"):
        return "bilibili"
    if _host_matches_domain(host, "douyin.com") or _host_matches_domain(host, "iesdouyin.com"):
        return "douyin"
    if any(_host_matches_domain(host, domain) for domain in ("youtube.com", "youtu.be", "googlevideo.com")):
        return "youtube"
    return "default"


def cookie_profile_status(path: Path, now: int | None = None) -> CookieProfileStatus:
    if not path.is_file():
        return CookieProfileStatus(state="not_configured", configured=False, usable=False)
    try:
        content = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return CookieProfileStatus(state="invalid", configured=True, usable=False)

    current = int(time.time()) if now is None else now
    total = valid = expired = session = 0
    future_expiries: list[int] = []
    for raw_line in content.splitlines():
        line = raw_line.strip()
        if not line or (line.startswith("#") and not line.startswith("#HttpOnly_")):
            continue
        if line.startswith("#HttpOnly_"):
            line = line.removeprefix("#HttpOnly_")
        fields = line.split("\t")
        if len(fields) < 7:
            continue
        total += 1
        try:
            expiry = int(float(fields[4]))
        except ValueError:
            continue
        if expiry <= 0:
            session += 1
        elif expiry <= current:
            expired += 1
        else:
            valid += 1
            future_expiries.append(expiry)

    usable = valid > 0 or session > 0
    earliest = min(future_expiries) if future_expiries else None
    if total == 0:
        state = "invalid"
    elif not usable:
        state = "expired" if expired > 0 else "invalid"
    elif valid > 0 and earliest is not None and earliest <= current + 7 * 24 * 60 * 60:
        state = "expiring"
    elif valid > 0:
        state = "valid"
    else:
        state = "session"
    return CookieProfileStatus(
        state=state,
        configured=True,
        usable=usable,
        total_count=total,
        valid_count=valid,
        expired_count=expired,
        session_count=session,
        earliest_expiry=earliest,
    )


def cookie_names(path: Path) -> set[str]:
    if not path.is_file():
        return set()
    try:
        content = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return set()
    names: set[str] = set()
    for raw_line in content.splitlines():
        line = raw_line.strip()
        if not line or (line.startswith("#") and not line.startswith("#HttpOnly_")):
            continue
        if line.startswith("#HttpOnly_"):
            line = line.removeprefix("#HttpOnly_")
        fields = line.split("\t")
        if len(fields) >= 7:
            names.add(fields[5])
    return names


def youtube_login_cookies_present(path: Path) -> bool:
    names = cookie_names(path)
    sid_names = {"SAPISID", "__Secure-1PAPISID", "__Secure-3PAPISID"}
    return "LOGIN_INFO" in names and bool(names & sid_names)


def _login_status_path(config_dir: Path) -> Path:
    return config_dir / _LOGIN_STATUS_FILENAME


def _load_login_statuses(config_dir: Path) -> dict[str, dict[str, Any]]:
    try:
        data = json.loads(_login_status_path(config_dir).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def save_cookie_login_status(config_dir: Path, profile: str, login_state: str) -> None:
    profile = normalize_cookie_profile(profile)
    if login_state not in {"valid", "invalid", "unknown"}:
        return
    statuses = _load_login_statuses(config_dir)
    statuses[profile] = {"state": login_state, "checked_at": int(time.time())}
    config_dir.mkdir(parents=True, exist_ok=True)
    _login_status_path(config_dir).write_text(json.dumps(statuses, indent=2), encoding="utf-8")


def clear_cookie_login_status(config_dir: Path, profile: str) -> None:
    profile = normalize_cookie_profile(profile)
    statuses = _load_login_statuses(config_dir)
    if profile not in statuses:
        return
    del statuses[profile]
    path = _login_status_path(config_dir)
    if statuses:
        path.write_text(json.dumps(statuses, indent=2), encoding="utf-8")
    else:
        path.unlink(missing_ok=True)


def cookie_profile_statuses(config_dir: Path) -> dict[str, CookieProfileStatus]:
    login_statuses = _load_login_statuses(config_dir)
    statuses: dict[str, CookieProfileStatus] = {}
    for profile in COOKIE_PROFILES:
        status = cookie_profile_status(cookie_file_path(config_dir, profile))
        cached = login_statuses.get(profile)
        if status.configured and isinstance(cached, dict):
            state = cached.get("state")
            checked_at = cached.get("checked_at")
            if state in {"valid", "invalid", "unknown"}:
                status.login_state = state
            if isinstance(checked_at, int):
                status.login_checked_at = checked_at
        statuses[profile] = status
    return statuses


def configured_cookie_profiles(config_dir: Path) -> dict[str, bool]:
    return {profile: status.usable for profile, status in cookie_profile_statuses(config_dir).items()}


def cookie_file_path(config_dir: Path, profile: str) -> Path:
    profile = normalize_cookie_profile(profile)
    if profile == "default":
        return config_dir / "cookies.txt"
    return config_dir / f"cookies-{profile}.txt"


def cookie_file_for_url(config_dir: Path, url: str) -> Path | None:
    profile = cookie_profile_for_url(url)
    candidate = cookie_file_path(config_dir, profile)
    if cookie_profile_status(candidate).usable:
        return candidate
    default = cookie_file_path(config_dir, "default")
    return default if cookie_profile_status(default).usable else None


def normalize_cookies(content: str, default_domain: str | None = None) -> str | None:
    stripped = content.strip()
    if not stripped:
        return None
    if _looks_like_netscape(stripped):
        return stripped + "\n"
    if stripped.startswith("{") or stripped.startswith("["):
        return _json_to_netscape(stripped, default_domain)
    if default_domain:
        return _header_to_netscape(stripped, default_domain)
    raise HTTPException(
        status_code=status.HTTP_400_BAD_REQUEST,
        detail="Cookies must be Netscape cookies.txt format or a supported JSON cookie export.",
    )


def _looks_like_netscape(content: str) -> bool:
    lines = [line.strip() for line in content.splitlines() if line.strip() and (not line.startswith("#") or line.startswith("#HttpOnly_"))]
    return any(len(line.split("\t")) >= 7 for line in lines)


def _json_to_netscape(content: str, default_domain: str | None = None) -> str:
    try:
        data = json.loads(content)
    except json.JSONDecodeError as exc:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid cookies JSON.") from exc

    cookies = _extract_cookie_list(data)
    lines = [_HEADER.rstrip()]
    for cookie in cookies:
        line = _cookie_to_netscape_line(cookie, default_domain)
        if line:
            lines.append(line)
    if len(lines) == 1:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No usable cookies were found in the JSON export.",
        )
    return "\n".join(lines) + "\n"


def _extract_cookie_list(data: Any) -> list[dict[str, Any]]:
    if isinstance(data, list):
        return [item for item in data if isinstance(item, dict)]
    if isinstance(data, dict):
        for key in ("cookies", "cookie", "data"):
            value = data.get(key)
            if isinstance(value, list):
                return [item for item in value if isinstance(item, dict)]
    return []


def _header_to_netscape(content: str, default_domain: str) -> str:
    candidate = content.strip()
    if candidate.lower().startswith("cookie:"):
        candidate = candidate.split(":", 1)[1].strip()
    pairs: list[dict[str, Any]] = []
    ignored = {"domain", "path", "expires", "max-age", "samesite", "secure", "httponly"}
    for raw_pair in candidate.split(";"):
        if "=" not in raw_pair:
            continue
        name, value = raw_pair.split("=", 1)
        name = name.strip()
        value = value.strip()
        if not name or name.lower() in ignored or any(char in name for char in "\r\n\t"):
            continue
        if any(char in value for char in "\r\n\t"):
            continue
        pairs.append({"name": name, "value": value, "domain": default_domain, "path": "/", "secure": True})
    lines = [_HEADER.rstrip(), *filter(None, (_cookie_to_netscape_line(cookie, default_domain) for cookie in pairs))]
    if len(lines) == 1:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="No usable cookies were found in the Cookie header.")
    return "\n".join(lines) + "\n"


def _cookie_to_netscape_line(cookie: dict[str, Any], default_domain: str | None = None) -> str | None:
    name = _string_value(cookie, "name")
    value = _string_value(cookie, "value")
    domain = _string_value(cookie, "domain") or _string_value(cookie, "host") or _string_value(cookie, "host_key") or default_domain
    if not name or value is None or not domain:
        return None

    path = _string_value(cookie, "path") or "/"
    include_subdomains = "TRUE" if domain.startswith(".") or bool(cookie.get("hostOnly") is False) else "FALSE"
    secure = "TRUE" if bool(cookie.get("secure")) else "FALSE"
    expires = _expires_value(cookie)
    return "\t".join([domain, include_subdomains, path, secure, expires, name, value])


def _string_value(cookie: dict[str, Any], key: str) -> str | None:
    value = cookie.get(key)
    if value is None:
        return None
    return str(value)


def _expires_value(cookie: dict[str, Any]) -> str:
    for key in ("expirationDate", "expires", "expiry", "expiration_date"):
        value = cookie.get(key)
        if value is None:
            continue
        try:
            return str(max(0, int(float(value))))
        except (TypeError, ValueError):
            continue
    return "0"
